spring:
  application:
    name: itunes-client

server:
  port: 8085
  
broccoli:
  params:
    max-result: 5

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
