version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v1.8.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
      - google
      - itunes
      - eureka

  cadvisor:
    image: google/cadvisor:v0.27.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8090:8080
    expose:
      - 8090

  grafana:
    image: grafana/grafana:4.6.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana

  google:
    build: ../broccoli-eureka-client-google/
    ports:
      - 8084:8084
    volumes:
      - ../broccoli-eureka-client-google/:/code
      
  itunes:
    build: ../broccoli-eureka-client-itunes/
    ports:
      - 8085:8085
    volumes:
      - ../broccoli-eureka-client-itunes/:/code
      
  eureka:
    build: ../broccoli-eureka-server/
    ports:
      - 8761:8761
    volumes:
      - ../broccoli-eureka-server/:/code

  authentication:
    build: ../broccoli-eureka-client-authentication/
    ports:
      - 8086:8086
    volumes:
      - ../broccoli-eureka-client-authentication/:/code

  postgres:
    image: postgres:9.4
    volumes:
      - ./docker-entrypoint-initdb.d/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: broccoli
      POSTGRES_PASSWORD: broccoli
      POSTGRES_DB: broccoli
    
