version: '3.6'

services:
  prometheus:
    image: prom/prometheus:v1.8.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - ./data/prometheus/:/prometheus
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    expose:
      - 9090
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
      - google
      - itunes
      - eureka

  cadvisor:
    image: google/cadvisor:v0.27.3
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8090:8080
    expose:
      - 8090

  grafana:
    image: grafana/grafana:4.6.3
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana/:/var/lib/grafana

  google:
    build: ../broccoli-eureka-client-google/
    ports:
      - 8084:8084
    volumes:
      - ../broccoli-eureka-client-google/:/code
      
  itunes:
    build: ../broccoli-eureka-client-itunes/
    ports:
      - 8085:8085
    volumes:
      - ../broccoli-eureka-client-itunes/:/code
      
  eureka:
    build: ../broccoli-eureka-server/
    ports:
      - 8761:8761
    volumes:
      - ../broccoli-eureka-server/:/code
  cas:
    image: apereo/cas:v5.1.3
    ports:
      - "8082:8080"
    volumes:
      - ./cas/tmp:/root/.m2/repository/
      - ./cas/cas.properties:/cas-overlay/etc/cas/config/cas.properties:ro
      - ./cas/All-10000005.json:/cas-overlay/etc/cas/services/All-10000005.json:ro
      - ./cas/pom.xml:/cas-overlay/pom.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/cas"]
      interval: 1m30s
      timeout: 30s
      retries: 5
