spring:
  application:
    name: google-client

server:
  port: 8084

broccoli:
  params:
    max-result: 5

management:
  endpoints:
    web:
      exposure:
        include: prometheus

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8761/eureka/
