global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: my-project
rule_files:
- alert.rules
scrape_configs:
- job_name: app
  scrape_interval: 5s
  metrics_path: /prometheus
  static_configs:
  - targets:
    - app:8080
- job_name: cadvisor
  scrape_interval: 5s
  metrics_path: /metrics
  static_configs:
  - targets:
    - cadvisor:8090